Section "Monitor"
  Identifier "HDMI-1"
  Option "Rotate" "normal"
EndSection

Section "Monitor"
  Identifier "HDMI-2"
  Option "Rotate" "normal"
EndSection

Section "Device"
  Identifier "modesetting_device"
  Driver "modesetting"
  Option "kmsdev" "/dev/dri/card1"
  Option "AccelMethod" "glamor"
EndSection
